# Generated by Django 4.2 on 2023-05-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_name', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
